// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsopguyucqkmjrkxaztc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzb3BndXl1Y3FrbWpya3hhenRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Njc5NDcsImV4cCI6MjA3MDM0Mzk0N30.FcuTjayYMTcH7q1lvoTo1SVqwNe_s8slmJMfrcBAehI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});